services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: []
    environment:
      TOKEN: #MTEyNDAxNzQwOTQ2NTAwNDExMw.GW733Q.m7x-tJsMbAgA27Xw0VPs5LkrQ_x-CmVpns-yEw
